#!/bin/bash

OUT_DIR="./"
OUT_NAME="backup.tar"
EXTENSIONS=""

while getopts :d:o:e option
do
	case "${option}"
	in
		d) OUT_DIR=${OPTARG};;
		o) OUT_NAME=${OPTARG};;
		e) EXTENSIONS=${OPTARG};;
		\?) echo "Unknown option: -$OPTARG" >&2 
			exit 1;;
		:) echo "what"
			exit 2;;
	esac
done

echo $OUT_DIR
echo $OUT_NAME
echo $EXTENSIONS

